### ISSUE TITLE
Wondering why the node name and pin names aren't capitalized?

### ISSUE THREAD

**Issue by HamasWaqar** [UniversalGRAMM/UGRAMM#17]
Hey @ombhilare999,

For the device model graph and application DFG, why aren't the node names and pin names not capitalized? I thought the convention for GRAMM was to capitalize all strings to make the program case insensitive. Just wondering as 

![image](https://github.com/user-attachments/assets/339b0493-1615-4ee9-a93f-e9ab667e51c7)

Also, should we not store the load and driver pin in the node config? I think this will make the code much user user-friendly instead of using the boost::get statement in the route function.

**Comment by ombhilare999** [comment]
Hi,

I believe I missed the normalizing GNAME attribute.

https://github.com/UniversalGRAMM/UGRAMM/blob/master/src%2Futilities.cpp#L688-L689

You can really store the uppercase version of the GNAME attribute into the gNames array and since pinName is parsed from gNames[] itself; We will have that normalized as well. 

Do note that you may need to normalize the driver and load attributes from application sir dot well.
